### ISSUE TITLE
saved password '§' turns to 'Â§' when copied to clipboard or shown when editing

### ISSUE THREAD

**Issue by pittagurneyi** [IJHack/qtpass#91] opened 2015-08-27 15:33 UTC
Hi, 

thank you for this excellent software.

Sadly, I found a rather problematic error. When saving a password with § in it, the actions of copy to clipboard or showing the password when editing, turn it into Â§, which alters the password.

If someone could perhaps test it, to make sure that the issue is not solely on my system, that would be great.

Using pass on the console returns the correct password. Should there in fact be an issue with qtpass, it would be really helpful to get a list of characters, that exhibit this sort of problem, to verify all existing passwords against possible corruption.

Thank you!

**Comment by annejan** [comment] 2015-08-27 15:39
Purely off the top of my head this looks like an **encoding** issue.
I'm pretty sure the clipboard either expects UTF-8 and is presented an ISO-8859 string or vice-versa.

Would you mind telling me which platform (and/or window manager) you are using?

**Comment by pittagurneyi** [comment] 2015-08-27 16:18
Gentoo Linux, KDE Plasma5

The problem is, that, upon clicking "show password" (or whatever it says in english), in the edit dialog, it also shows the password as Â§.

**Comment by annejan** [comment] 2015-08-27 16:35
Thanks, I run the same (well, Arch) on my main laptop, so that should make debugging pretty easy.

The fact it also shows the password corrupted makes it even easier . . 
Apparently the process that fetches the password already makes the encoding mistake.
Will try and look into this as soon as possible, thanks for finding and the clear description!

**Comment by pittagurneyi** [comment] 2015-08-27 16:54
Thank you for looking into it!

If you could notify me when you have the patch ready, I'd like to fix this on my system as soon as possible.

**Comment by pittagurneyi** [comment] 2015-08-28 09:38
It looks to me like process->readAllStandardOutput is not properly read as QString utf8.

Perhaps QString::fromUtf8 would help.

**Comment by pittagurneyi** [comment] 2015-08-28 09:58
I just tested it and the password is received okay. Just plain § now.

Just made sure all process->readAllStandardOutput is properly wrapped in QString::fromUtf8 in mainwindows.cpp

Since I don't know the whole picture of how the program is written and don't have the time to work through it all, you have to make sure this actually works and doesn't create problems elsewhere.

I'll look forward to hearing from you.

**Comment by annejan** [comment] 2015-08-28 10:28
Wow, thanks for the effort!!

Will do some more testing (on Linux, Mac and Windows) tonight . . 
Yesterday only had time to do a quick test on OSX and there it worked as-is . . so can easily do regression-testing..

**Comment by pittagurneyi** [comment] 2015-08-28 10:52
Well my shell environment and complete system should be solidly utf8 only. Any way of testing why it went wrong with my system? Why QProcess returns non-utf8 by default?

**Comment by annejan** [comment] 2016-09-26 19:53
Closed by #199

**Closed by annejan** 2016-09-26 19:53 UTC
Labels: bug, can't reproduce, help wanted
