### ISSUE TITLE
OSX: Qt-window closed only reappears when 'active' and using tray incon

### ISSUE THREAD

**Issue by dennisdegreef** [IJHack/qtpass#77] opened 2015-08-01 21:42 UTC
Whenever I close the Qt-window of QtPass, I can Cmd+Tab back and forth between applications without QtPass returning.

Only when QtPass is selected as active app, and when I press the tray icon, the Qt-window reappears.

@annejan I've showed you this behaviour :)

**Comment by annejan** [comment] 2015-11-23 20:02
The OSX implementation of the TrayIcon needs some more love since it should (in my opinion) also hide the dock icon when "closed" which it currently doesn't (on El Capitan at-least).

**Comment by annejan** [comment] 2016-01-31 22:28
Should be fixed by now .. can't reproduce anymore at-least on my box.

**Closed by annejan** 2016-01-31 22:28 UTC
Labels: enhancement, OSX

**Comment by dennisdegreef** [comment] 2016-02-01 21:17
I haven't tested it yet, but many thanks for your effort on resolving this! :+1:

**Comment by annejan** [comment] 2016-02-01 21:27
Still gonna do a little change on hiding the Dock icon when minimised to tray.
