### ISSUE TITLE
Boxes already checked for user in .gpg-id file

### ISSUE THREAD

**Issue by kenji21** [IJHack/QtPass#390] opened 2018-05-09 04:31 UTC
We share password (and login) using passwordstore command and QtPass (thanks for this nice software) across our team
One limitation is that we can't easily know who can use password in which subfolder, let's say in this configuration

```
a.com/.gpg-id (3E286FDFD9232A11/userA 3F01457BC926AD78/userB)
a.com/login
b.com/.gpg-id (3E286FDFD9232A11/userA 46D6CAF30BFC2B4F/userC)
b.com/login
```

When clicking a.com, then "Users",
Actual:
 no checkboxes are checked at all

Expected:
 checkboxes of userA and userB should be checked, but not userC of course

Regards

**Comment by Alixerid** [comment] 2018-05-11 09:44
This seems to be a symptom/duplicate of #205:
(On windows) the `.gpg-id` files in subfolders are ignored. When opening the dialog the checkboxes are filled with the permissions that are set by the `.gpg-id` in the root folder of the passwordstore only.

Has there been any progress with this issue? This problem with not parsing the `.gpg-id`s in subfolders is somewhat of a roadblock for using QtPass in teams (on Windows).

**Comment by Alixerid** [comment] 2018-06-06 07:28
@annejan Thanks for tagging! I was wondering why you tagged this as regression. Was there a fix for this bug in a previous release? (Honest and humble question. Sorry, if it is a stupid one.)

I was trying to read the code and identify the problem. Since the bug only occurs on Windows, I was suspecting that it might either be an issue with Qt on Windows or it is something about file path specification (non-POSIX etc.) that interferes in the case distinction and iteration over folders and parent folders. Has anyone pinpointed the problem?

**Comment by annejan** [comment] 2018-06-06 08:29
@Alixerid the reason for the *regression* tag is that it used to work, so somewhere while changing other stuff this broke.

This issue is something I am currently looking into, and hope to be able to pin down this week.

**Comment by Alixerid** [comment] 2018-06-06 14:53
Thanks, @annejan, guess I hadn't realized that this worked before. 
Sounds great that you are looking into it. Best of luck pinning it down!

**Comment by annejan** [comment] 2018-07-13 08:47
Thank you for investigating and fixing, yes, a PR would be very welcome @kenji21

**Comment by kenji21** [comment] 2018-07-13 10:22
There it is: PR https://github.com/IJHack/QtPass/pull/403

**Comment by annejan** [comment] 2018-07-13 21:34
Tested and merged

**Closed** 2018-07-13 21:34 UTC
Labels: bug, duplicate, regression

**Comment by kenji21** [comment] 2019-01-16 15:59
Hi,

As there are 100 commits to master since last release (1.2.3), when will a next release be available (with this fix) ?
