### ISSUE TITLE
Program does not run in Windows 10

### ISSUE THREAD

**Issue by JayMaree** [IJHack/QtPass#123] opened 2015-12-13 18:42 UTC
It just won't start ( no process in task manager ), I've tried multiple compatibility settings. No luck.

**Comment by annejan** [comment] 2015-12-15 11:14
Installing a Windows 10 VM from modern.ie and I'll have a look.

Might be fixed in master already since there was an issue with https://github.com/IJHack/qtpass/pull/113
What version are you currently using?

**Comment by JayMaree** [comment] 2015-12-15 15:09
Well, I've just installed the .exe which is available on the releases page. After installation I tried to launch the application, but nothing happens.

Windows Event Viewer creates this output:
Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: qtpass.exe
P2: 0.0.0.0
P3: 564c5cc3
P4: Qt5Core.dll
P5: 5.5.1.0
P6: 777a675f
P7: c0000005
P8: 001a6930
P9: 
P10:

**Comment by tuphamnguyen** [comment] 2015-12-26 01:47
I ran into the same problem on Windows 10 (Used the installer from releases). Have tried running in administrative and compatibility mode for Windows 7 and 8 but neither helped.
Opening the app displays the following:
![APPCRASH](http://imgur.com/nYDAx7e.png)

Windows Event Viewer
![Windows Event View](http://imgur.com/b3TURTR.png)
 qtpass.exe 
   0.0.0.0 
   564c5cc3 
   Qt5Core.dll 
   5.5.1.0 
   777a675f 
   c0000005 
   001a6930 
   da0 
   01d13f7e400e4b38 
   C:\Program Files (x86)\QtPass\qtpass.exe 
   C:\Program Files (x86)\QtPass\Qt5Core.dll 
   ab4e72ec-0f5b-446c-b78b-b27f909d89a0

**Comment by kevinoid** [comment] 2015-12-27 18:24
For what it's worth, I was seeing the same behavior on Windows 7 after a clean installation of [qtpass-1.0.5.exe](https://github.com/IJHack/qtpass/releases/download/v1.0.5/qtpass-1.0.5.exe) from the Releases page.  On Windows 7 the Event Log recorded the following information:

```
Log Name:      Application
Source:        Application Error
Date:          12/27/2015 11:09:15 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
Description:
Faulting application name: qtpass.exe, version: 0.0.0.0, time stamp: 0x564c5cc3
Faulting module name: Qt5Core.dll, version: 5.5.1.0, time stamp: 0x777a675f
Exception code: 0xc0000005
Fault offset: 0x001a6930
Faulting process id: 0x1044
Faulting application start time: 0x01d140d1b109f01d
Faulting application path: C:\Program Files (x86)\QtPass\qtpass.exe
Faulting module path: C:\Program Files (x86)\QtPass\Qt5Core.dll
Report Id: efdb443f-acc4-11e5-9961-28d244016781
```

Installing [qtpass-1.0.5.1.exe](https://ci.appveyor.com/api/buildjobs/3xsypnk0v9jf49s0/artifacts/Output/qtpass-1.0.5.1.exe) built 2015-12-22 9:53:47 appears to have solved the issue for me.

**Comment by annejan** [comment] 2015-12-27 21:41
I'll see if I can do some more testing and release 1.0.6 with the current fixes tomorrow..

**Comment by annejan** [comment] 2016-01-31 09:41
Have had no issues since December 22nd build . . 
Closing, feel free to re-open or open a new one if Windows build starts breaking again.

**Comment by o-alquimista** [comment] 2019-11-19 15:47
Please re-open this. I can reproduce this with version 1.3.1, the latest .exe installable available [here](https://qtpass.org/downloads#Windows). Fresh Windows 10 Pro installation.

**Comment by annejan** [comment] 2019-12-02 16:05
I have tried to replicate this . . unfortunately I'm not going to buy a Windows 10 Pro 
So I tried with a VM from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

And however I try I can't make QtPass not start from fresh install . .

Have you tried removing the config @o-alquimista with REGEdit?
`Windows registry: HKEY_CURRENT_USER\Software\IJhack\QtPass`

**Comment by sialvi** [comment] 2020-12-29 07:43
I was facing the same issue with version 1.3.2 downloaded from qtpass [site](https://qtpass.org/) but issue got resolved with version 1.3.3 downloaded from [link](https://ci.appveyor.com/project/annejan/qtpass/build/artifacts) given by @annejan

**Comment by jthomperoo** [comment] 2023-02-22 23:41
Just to add on here - suddenly my qtpass install on Windows stopped working after a Windows update (it 'launched' but the window would never appear on the screen, though I could see it in the taskbar, but couldn't access it). Following the steps to delete that registry entry got it working again for me.

**Comment by annejan** [comment] 2023-09-21 15:36
New release 1.4.0 tested on latest Windows versions

**Closed by annejan** 2023-09-21 15:36 UTC
Labels: bug, Windows, can't reproduce
