### ISSUE TITLE
v1.3.0 Data Not Showing

### ISSUE THREAD

**Issue by VwH387RXAF1m61wOtwuU** [IJHack/QtPass#465] opened 2019-08-20 13:02 UTC
v1.3.0 not showing entry data in main window, nor when Editing it. Password is there and when copied and pasted elsewhere, it is correct for that entry, but no other data shown. Verified what pass shows from command line, browserpass works fine too by showing username and password and otp, passforios works fine for all data still, so nothing wrong with my git repo. I have 1.2.3 and 1.3.0 installed on Mac 10.14.6 and everything works as expected with 1.2.3 still, but when I switch to 1.3.0, no data other than password is there and visible.

![pass_verify_commandline](https://user-images.githubusercontent.com/40723353/63349311-aaad6f80-c34a-11e9-895f-844c77dc33da.png)

![1 3 0_about](https://user-images.githubusercontent.com/40723353/63349129-48546f00-c34a-11e9-97cf-e4906bfbda45.png)

![1 3 0_details](https://user-images.githubusercontent.com/40723353/63349139-50141380-c34a-11e9-8ba7-b3671c88e33c.png)

![1 2 3_about](https://user-images.githubusercontent.com/40723353/63349146-57d3b800-c34a-11e9-96c5-b1b01a5a7592.png)

![1 2 3_details](https://user-images.githubusercontent.com/40723353/63349157-5d310280-c34a-11e9-845d-35509da06606.png)

**Comment by annejan** [comment] 2019-08-20 13:04
Interesting, seems the auto-templating is broken . . 

Will look into it after diner.

**Comment by VwH387RXAF1m61wOtwuU** [comment] 2019-08-20 14:23
thanks, I added fields in that example to template in settings and I can see them now in main window only when added to default template override, but when you edit the entry, there is nothing there, see attached.

Also, on other entries, I am not seeing the new functionality about OTP inside QTPass, it just shows the otpauth config line, no way that I see to actually copy of current OTP code for that entry, am I missing something there?

![Screen Shot 2019-08-20 at 10 19 44 AM](https://user-images.githubusercontent.com/40723353/63355587-e26de480-c355-11e9-9240-d0821607d636.png)

![Screen Shot 2019-08-20 at 10 20 01 AM](https://user-images.githubusercontent.com/40723353/63355599-e7329880-c355-11e9-8215-6871f435f60b.png)

**Comment by annejan** [comment] 2019-08-20 16:01
I'll have to look into the OTP feature, since I didn't write it myself . . hope to have some time for that tomorrow.

**Comment by VwH387RXAF1m61wOtwuU** [comment] 2019-08-20 18:25
thanks, also let me know when the next release is planned to drop with default auto-template fixed.

**Comment by annejan** [comment] 2019-08-22 11:33
I'm hoping to be able to fix these issues before next Monday.

**Comment by Spheerys** [comment] 2019-08-31 06:59
I have the same issue : editing is empty

**Comment by schmunk42** [comment] 2019-09-05 15:42
Same here, this is rather suboptimal, could you please look into it or is there a workaround?

**Comment by waldner** [comment] 2019-09-10 11:16
> Same here, this is rather suboptimal, could you please look into it or is there a workaround?

For now I'm using "pass edit" by hand but of course that's suboptimal too.

**Comment by annejan** [comment] 2019-09-10 11:19
This should be fixed in upcoming (this week) 1.3.1 release, see #473

**Comment by waldner** [comment] 2019-09-19 13:58
Any estimated date for the 1.3.1 release?

**Comment by kpwd** [comment] 2019-09-24 03:09
I have the same issue as this.

**Comment by t04z** [comment] 2019-09-25 20:06
same issue on arch

**Comment by projectq-io** [comment] 2019-09-26 08:38
Hi,
I've downgraded to 1.2.3 but the same issue here, opening qtpass is OK, I see all my password, but when clicking on one, nothing appear on the right panel :(.

**Comment by Spheerys** [comment] 2019-10-02 16:38
For me the issue is not closed.

Under Arch, you can easily downgrade to qtpass 1.2.3 by following this steps : 
-  downloading the previous package here : https://archive.archlinux.org/packages/q/qtpass/
- install it with sudo pacman -U qtpass-1.2.3-1-x86_64.pkg.tar.xz
- add qtpass on the line IgnorePkg of the /etc/pacman.conf file

**Comment by annejan** [comment] 2019-10-02 16:38
> For me the issue is not closed.

Have you tried 1.3.1 @Spheerys ?

**Comment by Spheerys** [comment] 2019-10-02 16:40
Oh... the 1.3.1 is not avaible on AUR for the moment.
I will mark this package as outdated and I will come back here :)

**Comment by Spheerys** [comment] 2019-10-02 16:55
In fact I can't find any official info about 1.3.1.
On  https://github.com/IJHack/QtPass the last tagged version is still the 1.3.0...

**Comment by annejan** [comment] 2019-10-02 16:58
Was only released earlier today https://github.com/IJHack/QtPass/releases
https://github.com/IJHack/QtPass/releases/tag/v1.3.1

So will probably take a couple more hours or a day to trickle down.

**Comment by Spheerys** [comment] 2019-10-03 20:05
This issue is closed with 1.3.1.
thanks ;)

**Closed** 2019-10-07 11:57 UTC
